### ISSUE TITLE
Add Unit Tests, Comments, and Documentation/Docstrings

### ISSUE THREAD

**Issue by UpstreamData** [UpstreamData/pyasic#8]
Most files need unit tests, comments, and documentation/typing added to them.

Current unit tests are located in `.tests`.

- Docstrings in `rpc` are mostly done, these are all base level implementations of the miner APIs, although some standardization across files and possibly improved type hinting would be useful.
- Unit tests for `network` have been written, but could always be better.
- Generally all files need some level of comments added, in my opinion it is a good idea to be as descriptive as possible, as an end goal is for even novice programmers to be able to design a simple program with this repo.

### TODO:
- #### Add unit tests:
    - [ ]  `rpc`  - This may be tough, these rely on external connections heavily.
    - [ ] `ssh` - Extension of `rpc` essentially, this handles more external calls.
    - [ ] `web` - Extension of `rpc`, again, more external calls.
    - [ ]  `config` - Partially done, but could use more tests for different conversions.
    - [ ]  `miners`  - Same issue as `rpc`.  Partially done, with checks for initialization and data locations.
    - [x] `network` - The important parts here are done, such as making sure inputs turn into the right network values.
- #### Add docstrings/documentation:
    - [x] `rpc`  - Maybe slight improvements to standardization, but overall good.
    - [ ] `web` - A part of data collection alongside `rpc`.  Could be used in the documentation alongside `rpc` in the advanced section.
    - [ ] `ssh` - Another means of data collection.  Same idea, this is an advanced topic.
    - [ ] #124
    - [x]  `miners` - Auto generated with `generate_miners.py`, this generates the supported list and the files for each.
    - [x] `network` - Quite good.  Easy to follow, short, and simple.
    - [x] `settings` - Good enough, doesn't need a whole lot of mentions unless something changes.
- #### Additional Comments:
    - Overall the docs could use a restructure, I'm not sure what the best way to do this is, but things are a bit jumbled right now.

**Comment by jaysharma0909** [comment]
@UpstreamData Can I contribute to this issue?

**Comment by b-rowan** [comment]
Yeah, go for it.  There is still a lot of tests missing, and documentation is good, but could still use some more information.  Happy to provide specific is you need them, but this checklist here isn't really accurate anymore.

**Comment by pavankalyan224847** [comment]
hello is this issue up for grabs can i help with this issue ?

**Comment by b-rowan** [comment]
> hello is this issue up for grabs can i help with this issue ? 

Sure, this is just sort of an ongoing improvement issue.

**Comment by pavankalyan224847** [comment]
can you please update checklist so that it'll be helpfull to look into what all things should be implemented and we can start working on this issue
